import {createClient} from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{
const auth=req.headers.get("Authorization");if(!auth)throw new Error("Authentication required");const url=Deno.env.get("SUPABASE_URL")!,caller=createClient(url,Deno.env.get("SUPABASE_ANON_KEY")!,{global:{headers:{Authorization:auth}}}),admin=createClient(url,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const {data:{user},error:userError}=await caller.auth.getUser();if(userError||!user)throw new Error("Invalid session");const {data:root}=await admin.from("user_roles").select("roles!inner(role_code)").eq("user_id",user.id).eq("roles.role_code","root").maybeSingle();if(!root)throw new Error("Healthcarology Root access required");
const body=await req.json(),authority=String(body.authority_level||""),phone=String(body.admin_phone||"").replace(/[\s().-]/g,"");if(!body.name||!["city","state_province","country"].includes(authority)||!body.country_id||!body.admin_name||!body.admin_email||!/^\+[1-9]\d{7,14}$/.test(phone))throw new Error("Complete the department, authority, country, administrator, email, and international phone fields");if(authority!=="country"&&!String(body.province_name||"").trim())throw new Error("Select a state or province");if(authority==="city"&&!String(body.city_name||"").trim())throw new Error("Select a city");
const countryId=Number(body.country_id),province=String(body.province_name||"").trim(),city=String(body.city_name||"").trim();
const findOrCreate=async(type:string,name:string,parentId:string|null)=>{let query=admin.from("health_jurisdictions").select("id").eq("country_id",countryId).eq("jurisdiction_type",type);if(type==="state_province")query=query.eq("province_name",province);else if(type==="city")query=query.eq("city_name",city);query=parentId?query.eq("parent_id",parentId):query.is("parent_id",null);const {data:found}=await query.maybeSingle();if(found)return found.id;const {data:made,error}=await admin.from("health_jurisdictions").insert({name,jurisdiction_type:type,authority_level:type,country_id:countryId,parent_id:parentId,province_name:type==="state_province"?province:null,city_name:type==="city"?city:null,boundary_reference:[province,city].filter(Boolean).join(" / "),created_by:user.id}).select("id").single();if(error)throw error;return made.id};
const {data:country,error:countryError}=await admin.from("countries").select("default_name").eq("id",countryId).single();if(countryError)throw countryError;const countryJurisdiction=await findOrCreate("country",country.default_name,null),stateJurisdiction=authority==="country"?null:await findOrCreate("state_province",province,countryJurisdiction),jurisdictionId=authority==="country"?countryJurisdiction:authority==="state_province"?stateJurisdiction:await findOrCreate("city",city,stateJurisdiction);
const {error:updateError}=await admin.from("health_jurisdictions").update({name:String(body.name).trim(),authority_level:authority,province_name:province||null,city_name:city||null,boundary_reference:[country.default_name,province,city].filter(Boolean).join(" / ")}).eq("id",jurisdictionId);if(updateError)throw updateError;
const password="Temp#123";const {data:created,error:createError}=await admin.auth.admin.createUser({email:String(body.admin_email).toLowerCase(),phone,password,email_confirm:true,phone_confirm:true,user_metadata:{display_name:body.admin_name},app_metadata:{must_change_password:true}});if(createError)throw createError;
const {data:role,error:roleError}=await admin.from("roles").select("id").eq("role_code","health_department_admin").single();if(roleError)throw roleError;const {error:memberError}=await admin.from("health_department_memberships").insert({jurisdiction_id:jurisdictionId,user_id:created.user.id,role_id:role.id});if(memberError)throw memberError;await admin.from("user_roles").insert({user_id:created.user.id,role_id:role.id,scope:`health:${jurisdictionId}`});return new Response(JSON.stringify({jurisdiction_id:jurisdictionId,name:body.name,admin_email:created.user.email,temporary_password:password,must_change_password:true,login_url:`${url.replace(/\/$/,"")}/health-department`}),{status:201,headers:{...cors,"Content-Type":"application/json"}})
}catch(error){return new Response(JSON.stringify({error:error.message}),{status:400,headers:{...cors,"Content-Type":"application/json"}})}});
