-- Healthcarology operational workflows. User-requested rules are represented as
-- stable codes; labels can be translated without changing clinical history.

insert into public.roles(role_code,role_name,description,access_level) values
 ('platform_agent','Healthcarology Agent','Creates and supports facilities for Healthcarology',1),
 ('lab_supervisor','Laboratory Supervisor','Validates laboratory results before release',3)
on conflict(role_code) do update set role_name=excluded.role_name,description=excluded.description;

create sequence if not exists public.facility_number_seq;
alter table public.facilities
  add column facility_number text unique,
  add column owner_name text,
  add column owner_email text,
  add column owner_phone text,
  add column emergency_contact_name text,
  add column emergency_contact_email text,
  add column emergency_contact_phone text,
  add column street_address text,
  add column city_name text,
  add column state_province text,
  add column postal_code text,
  add column country_name text;
update public.facilities set facility_number='HC-FAC-'||lpad(nextval('public.facility_number_seq')::text,8,'0') where facility_number is null;
alter table public.facilities alter column facility_number set default 'HC-FAC-'||lpad(nextval('public.facility_number_seq')::text,8,'0'), alter column facility_number set not null;

create or replace function private.is_platform_agent() returns boolean language sql stable security invoker set search_path='' as $$
 select exists(select 1 from public.user_roles ur join public.roles r on r.id=ur.role_id where ur.user_id=(select auth.uid()) and r.role_code in ('root','platform_agent'))
$$;
alter policy facilities_root_write on public.facilities using(private.is_platform_agent()) with check(private.is_platform_agent());

-- Pharmacy inventory and visible dispensing progression.
create table public.pharmacy_locations(
 id bigint generated by default as identity primary key, facility_id uuid not null references public.facilities(id) on delete cascade,
 name text not null, active boolean not null default true, unique(facility_id,name)
);
create table public.medication_inventory_lots(
 id bigint generated by default as identity primary key, facility_id uuid not null references public.facilities(id) on delete cascade,
 pharmacy_location_id bigint not null references public.pharmacy_locations(id), medication_id bigint not null references public.medications(id),
 lot_number text not null, expiry_date date, quantity_on_hand numeric(14,3) not null default 0 check(quantity_on_hand>=0),
 reorder_level numeric(14,3) not null default 0 check(reorder_level>=0), unit_cost numeric(14,4), created_at timestamptz not null default now(),
 unique(pharmacy_location_id,medication_id,lot_number)
);
create table public.inventory_movements(
 id bigint generated by default as identity primary key, facility_id uuid not null references public.facilities(id) on delete cascade,
 inventory_lot_id bigint not null references public.medication_inventory_lots(id), movement_type text not null check(movement_type in ('receipt','dispense','adjustment','transfer_in','transfer_out','return','waste')),
 quantity_delta numeric(14,3) not null check(quantity_delta<>0), reason text, actor_user_id uuid references auth.users(id), occurred_at timestamptz not null default now()
);
create table public.prescription_fulfillments(
 id bigint generated by default as identity primary key, facility_id uuid not null references public.facilities(id) on delete cascade,
 medication_order_id bigint not null unique references public.medication_orders(id) on delete cascade,
 status text not null default 'prescribed' check(status in ('prescribed','awaiting','dispensed','cancelled')),
 prescribed_at timestamptz not null default now(), awaiting_at timestamptz, dispensed_at timestamptz,
 dispensing_provider_id bigint references public.providers(id), quantity_dispensed numeric(14,3), inventory_lot_id bigint references public.medication_inventory_lots(id), notes text, updated_at timestamptz not null default now()
);
create table public.medication_adherence_events(
 id bigint generated by default as identity primary key, medication_order_id bigint not null references public.medication_orders(id) on delete cascade,
 patient_id bigint not null references public.patients(id) on delete cascade, scheduled_at timestamptz, reported_at timestamptz not null default now(),
 status text not null check(status in ('taken','missed','skipped')), notes text, reported_by_user_id uuid not null references auth.users(id)
);
create table public.medication_refill_requests(
 id bigint generated by default as identity primary key, medication_order_id bigint not null references public.medication_orders(id) on delete cascade,
 patient_id bigint not null references public.patients(id) on delete cascade, status text not null default 'requested' check(status in ('requested','approved','denied','filled','cancelled')),
 patient_message text, requested_at timestamptz not null default now(), reviewed_at timestamptz, reviewed_by_provider_id bigint references public.providers(id), response_message text
);

-- Appointment slots are the only units a patient can book.
create table public.provider_availability_slots(
 id bigint generated by default as identity primary key, facility_id uuid not null references public.facilities(id) on delete cascade,
 department_id bigint not null references public.departments(id), service_id bigint references public.services(id), provider_id bigint references public.providers(id),
 starts_at timestamptz not null, ends_at timestamptz not null, status text not null default 'available' check(status in ('available','booked','blocked','cancelled')),
 check(ends_at>starts_at), unique(facility_id,provider_id,starts_at)
);
create table public.appointments(
 id bigint generated by default as identity primary key, slot_id bigint not null unique references public.provider_availability_slots(id), facility_id uuid not null references public.facilities(id),
 patient_id bigint not null references public.patients(id), department_id bigint not null references public.departments(id), service_id bigint references public.services(id), provider_id bigint references public.providers(id),
 reason text, status text not null default 'booked' check(status in ('booked','confirmed','checked_in','completed','cancelled','no_show')),
 booked_by_user_id uuid not null references auth.users(id), booked_at timestamptz not null default now()
);
create or replace function public.book_available_slot(slot_to_book bigint,patient_to_book bigint,booking_reason text default null) returns bigint
language plpgsql security definer set search_path='' as $$
declare s public.provider_availability_slots%rowtype; result bigint;
begin
 if not exists(select 1 from public.patient_accounts where user_id=(select auth.uid()) and patient_id=patient_to_book)
    and not exists(select 1 from public.patient_accounts pa join public.patient_proxies px on px.proxy_patient_id=pa.patient_id where pa.user_id=(select auth.uid()) and px.target_patient_id=patient_to_book and px.active and px.can_manage_appointments)
    and not private.is_platform_root() then raise exception 'Patient booking access required'; end if;
 select * into s from public.provider_availability_slots where id=slot_to_book and status='available' and starts_at>now() for update;
 if s.id is null then raise exception 'This slot is no longer available'; end if;
 insert into public.appointments(slot_id,facility_id,patient_id,department_id,service_id,provider_id,reason,booked_by_user_id)
 values(s.id,s.facility_id,patient_to_book,s.department_id,s.service_id,s.provider_id,booking_reason,(select auth.uid())) returning id into result;
 update public.provider_availability_slots set status='booked' where id=s.id;
 return result;
end $$;

-- Diagnosis lifecycle: active diagnoses remain current until a provider closes them.
alter table public.diagnoses add column diagnosing_provider_id bigint references public.providers(id), add column closing_provider_id bigint references public.providers(id),
 add column clinical_status text not null default 'active' check(clinical_status in ('active','healed','closed','entered_in_error')),
 add column onset_at timestamptz not null default now(), add column closed_at timestamptz, add column closure_note text,
 add constraint diagnosis_closure_consistency check((clinical_status='active' and closed_at is null) or clinical_status in ('healed','closed','entered_in_error'));

-- Lab results stay inaccessible to doctors and patients until supervisor validation.
alter table public.lab_results add column validation_status text not null default 'draft' check(validation_status in ('draft','pending_validation','validated','rejected')),
 add column validated_by_provider_id bigint references public.providers(id), add column validated_at timestamptz, add column validation_note text;
drop policy if exists lab_results_access on public.lab_results;
create policy lab_results_released_read on public.lab_results for select to authenticated using(
 validation_status='validated' or private.is_platform_root() or public.current_role_code() in ('lab_tech','lab_supervisor')
);
create policy lab_results_laboratory_insert on public.lab_results for insert to authenticated with check(public.current_role_code() in ('root','lab_tech','lab_supervisor'));
create policy lab_results_laboratory_update on public.lab_results for update to authenticated using(public.current_role_code() in ('root','lab_tech','lab_supervisor')) with check(
 public.current_role_code() in ('root','lab_supervisor') or (public.current_role_code()='lab_tech' and validation_status in ('draft','pending_validation'))
);

-- Nephrology / dialysis core operational record.
create table public.dialysis_prescriptions(
 id bigint generated by default as identity primary key, facility_id uuid not null references public.facilities(id), patient_id bigint not null references public.patients(id), nephrologist_id bigint not null references public.providers(id),
 modality text not null check(modality in ('hemodialysis','peritoneal_dialysis','continuous_renal_replacement')), sessions_per_week smallint, duration_minutes integer,
 target_weight_kg numeric(6,2), dialyzer text, blood_flow_ml_min integer, dialysate_flow_ml_min integer, anticoagulation text, active boolean not null default true, prescribed_at timestamptz not null default now()
);
create table public.dialysis_sessions(
 id bigint generated by default as identity primary key, prescription_id bigint not null references public.dialysis_prescriptions(id), facility_id uuid not null references public.facilities(id), patient_id bigint not null references public.patients(id),
 station text, scheduled_at timestamptz not null, started_at timestamptz, ended_at timestamptz, status text not null default 'scheduled' check(status in ('scheduled','in_progress','completed','cancelled','missed')),
 pre_weight_kg numeric(6,2), post_weight_kg numeric(6,2), ultrafiltration_goal_ml integer, ultrafiltration_actual_ml integer, pre_vitals jsonb not null default '{}'::jsonb, post_vitals jsonb not null default '{}'::jsonb,
 access_type text, complications text, nurse_provider_id bigint references public.providers(id), closed_by_provider_id bigint references public.providers(id)
);

-- Surgery management: case scheduling, safety checklists, team, intra-op and recovery.
create table public.surgical_cases(
 id bigint generated by default as identity primary key, facility_id uuid not null references public.facilities(id), patient_id bigint not null references public.patients(id), encounter_id bigint references public.encounters(id),
 procedure_name text not null, diagnosis_id bigint references public.diagnoses(id), urgency text not null default 'elective' check(urgency in ('elective','urgent','emergency')),
 status text not null default 'planned' check(status in ('planned','scheduled','pre_op','in_operating_room','in_recovery','completed','cancelled')),
 scheduled_start timestamptz, scheduled_end timestamptz, operating_room text, lead_surgeon_id bigint references public.providers(id), anesthesia_type text, consent_verified boolean not null default false, created_at timestamptz not null default now()
);
create table public.surgical_case_team(
 surgical_case_id bigint not null references public.surgical_cases(id) on delete cascade, provider_id bigint not null references public.providers(id), team_role text not null, primary key(surgical_case_id,provider_id,team_role)
);
create table public.surgical_checklist_items(
 id bigint generated by default as identity primary key, surgical_case_id bigint not null references public.surgical_cases(id) on delete cascade,
 phase text not null check(phase in ('pre_op','sign_in','time_out','sign_out','recovery')), item text not null, completed boolean not null default false,
 completed_by_user_id uuid references auth.users(id), completed_at timestamptz
);
create table public.surgical_events(
 id bigint generated by default as identity primary key, surgical_case_id bigint not null references public.surgical_cases(id) on delete cascade,
 event_type text not null check(event_type in ('incision','medication','implant','specimen','blood_product','complication','closure','transfer')), occurred_at timestamptz not null default now(), details jsonb not null default '{}'::jsonb, recorded_by_user_id uuid not null references auth.users(id)
);

-- Tenant-aware access for new operational tables.
do $$ declare t text; begin foreach t in array array['pharmacy_locations','medication_inventory_lots','inventory_movements','prescription_fulfillments','provider_availability_slots','appointments','dialysis_prescriptions','dialysis_sessions','surgical_cases','surgical_case_team','surgical_checklist_items','surgical_events','medication_adherence_events','medication_refill_requests'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy pharmacy_locations_access on public.pharmacy_locations for all to authenticated using(private.is_platform_root() or private.is_facility_member(facility_id)) with check(private.is_platform_root() or private.is_facility_member(facility_id));
create policy inventory_lots_access on public.medication_inventory_lots for all to authenticated using(private.is_platform_root() or private.is_facility_member(facility_id)) with check(private.is_platform_root() or private.is_facility_member(facility_id));
create policy inventory_movements_access on public.inventory_movements for all to authenticated using(private.is_platform_root() or private.is_facility_member(facility_id)) with check(private.is_platform_root() or private.is_facility_member(facility_id));
create policy fulfillments_access on public.prescription_fulfillments for all to authenticated using(private.is_platform_root() or private.is_facility_member(facility_id) or exists(select 1 from public.medication_orders mo join public.patient_accounts pa on pa.patient_id=mo.patient_id where mo.id=medication_order_id and pa.user_id=(select auth.uid()))) with check(private.is_platform_root() or private.is_facility_member(facility_id));
create policy slots_visible on public.provider_availability_slots for select to authenticated using(status='available' or private.is_platform_root() or private.is_facility_member(facility_id));
create policy slots_staff_write on public.provider_availability_slots for all to authenticated using(private.is_platform_root() or private.is_facility_member(facility_id)) with check(private.is_platform_root() or private.is_facility_member(facility_id));
create policy appointments_access on public.appointments for select to authenticated using(private.is_platform_root() or private.is_facility_member(facility_id) or exists(select 1 from public.patient_accounts pa where pa.patient_id=appointments.patient_id and pa.user_id=(select auth.uid())));
create policy appointments_staff_write on public.appointments for all to authenticated using(private.is_platform_root() or private.is_facility_member(facility_id)) with check(private.is_platform_root() or private.is_facility_member(facility_id));
create policy adherence_access on public.medication_adherence_events for all to authenticated using(exists(select 1 from public.patient_accounts pa where pa.patient_id=medication_adherence_events.patient_id and pa.user_id=(select auth.uid())) or exists(select 1 from public.patients p where p.id=patient_id and p.facility_id is not null and private.is_facility_member(p.facility_id))) with check(exists(select 1 from public.patient_accounts pa where pa.patient_id=medication_adherence_events.patient_id and pa.user_id=(select auth.uid())));
create policy refill_access on public.medication_refill_requests for all to authenticated using(exists(select 1 from public.patient_accounts pa where pa.patient_id=medication_refill_requests.patient_id and pa.user_id=(select auth.uid())) or exists(select 1 from public.patients p where p.id=patient_id and p.facility_id is not null and private.is_facility_member(p.facility_id))) with check(exists(select 1 from public.patient_accounts pa where pa.patient_id=medication_refill_requests.patient_id and pa.user_id=(select auth.uid())) or exists(select 1 from public.patients p where p.id=patient_id and p.facility_id is not null and private.is_facility_member(p.facility_id)));
create policy dialysis_rx_access on public.dialysis_prescriptions for all to authenticated using(private.is_platform_root() or private.is_facility_member(facility_id)) with check(private.is_platform_root() or private.is_facility_member(facility_id));
create policy dialysis_sessions_access on public.dialysis_sessions for all to authenticated using(private.is_platform_root() or private.is_facility_member(facility_id)) with check(private.is_platform_root() or private.is_facility_member(facility_id));
create policy surgical_cases_access on public.surgical_cases for all to authenticated using(private.is_platform_root() or private.is_facility_member(facility_id)) with check(private.is_platform_root() or private.is_facility_member(facility_id));
create policy surgical_team_access on public.surgical_case_team for all to authenticated using(exists(select 1 from public.surgical_cases c where c.id=surgical_case_id and (private.is_platform_root() or private.is_facility_member(c.facility_id)))) with check(exists(select 1 from public.surgical_cases c where c.id=surgical_case_id and (private.is_platform_root() or private.is_facility_member(c.facility_id))));
create policy surgical_checklist_access on public.surgical_checklist_items for all to authenticated using(exists(select 1 from public.surgical_cases c where c.id=surgical_case_id and (private.is_platform_root() or private.is_facility_member(c.facility_id)))) with check(exists(select 1 from public.surgical_cases c where c.id=surgical_case_id and (private.is_platform_root() or private.is_facility_member(c.facility_id))));
create policy surgical_events_access on public.surgical_events for all to authenticated using(exists(select 1 from public.surgical_cases c where c.id=surgical_case_id and (private.is_platform_root() or private.is_facility_member(c.facility_id)))) with check(exists(select 1 from public.surgical_cases c where c.id=surgical_case_id and (private.is_platform_root() or private.is_facility_member(c.facility_id))));

grant select,insert,update,delete on public.pharmacy_locations,public.medication_inventory_lots,public.inventory_movements,public.prescription_fulfillments,public.medication_adherence_events,public.medication_refill_requests,public.provider_availability_slots,public.appointments,public.dialysis_prescriptions,public.dialysis_sessions,public.surgical_cases,public.surgical_case_team,public.surgical_checklist_items,public.surgical_events to authenticated;
grant usage,select on all sequences in schema public to authenticated;
revoke all on function public.book_available_slot(bigint,bigint,text) from public,anon;
grant execute on function public.book_available_slot(bigint,bigint,text) to authenticated;

create index inventory_expiry_idx on public.medication_inventory_lots(facility_id,expiry_date) where quantity_on_hand>0;
create index fulfillment_flow_idx on public.prescription_fulfillments(facility_id,status,updated_at desc);
create index available_slots_idx on public.provider_availability_slots(facility_id,starts_at) where status='available';
create index appointments_patient_idx on public.appointments(patient_id,booked_at desc);
create index adherence_patient_idx on public.medication_adherence_events(patient_id,reported_at desc);
create index dialysis_sessions_schedule_idx on public.dialysis_sessions(facility_id,scheduled_at);
create index surgical_cases_schedule_idx on public.surgical_cases(facility_id,scheduled_start);
