-- Healthcarology identifiers are immutable internal identifiers. National issuing
-- authority adapters may replace the generator only after country-specific approval.
create or replace function private.assign_healthcarology_unin() returns trigger language plpgsql security definer set search_path='' as $$
begin
  if new.snau is null or btrim(new.snau)='' then new.snau := 'HC-' || upper(replace(gen_random_uuid()::text,'-','')); end if;
  return new;
end $$;
create or replace function private.prevent_unin_change() returns trigger language plpgsql security definer set search_path='' as $$
begin
  if old.snau is distinct from new.snau then raise exception 'UNIN is permanent and cannot be changed'; end if;
  return new;
end $$;
revoke all on function private.assign_healthcarology_unin(),private.prevent_unin_change() from public,anon,authenticated;
drop trigger if exists assign_patient_unin on public.patients;
create trigger assign_patient_unin before insert on public.patients for each row execute function private.assign_healthcarology_unin();
drop trigger if exists prevent_patient_unin_change on public.patients;
create trigger prevent_patient_unin_change before update of snau on public.patients for each row execute function private.prevent_unin_change();
update public.patients set snau='HC-' || upper(replace(gen_random_uuid()::text,'-','')) where snau is null;
alter table public.patients alter column snau set not null;

create table public.facility_patient_mrns (
  facility_id uuid not null references public.facilities(id) on delete cascade,
  patient_id bigint not null references public.patients(id) on delete cascade,
  mrn text not null,
  assigned_at timestamptz not null default now(),
  primary key(facility_id,patient_id),
  unique(facility_id,mrn)
);

create table public.lab_reference_ranges (
  id bigint generated by default as identity primary key,
  facility_id uuid references public.facilities(id) on delete cascade,
  analyte_code text not null,
  analyte_name text not null,
  units text not null,
  sex text,
  age_min_days integer,
  age_max_days integer,
  normal_low numeric,
  normal_high numeric,
  critical_low numeric,
  critical_high numeric,
  effective_from date not null default current_date,
  effective_to date,
  check(normal_low is null or normal_high is null or normal_low<=normal_high),
  check(critical_low is null or normal_low is null or critical_low<=normal_low),
  check(critical_high is null or normal_high is null or critical_high>=normal_high)
);
alter table public.lab_results add column numeric_value numeric;
alter table public.lab_results add column reference_range_id bigint references public.lab_reference_ranges(id);
alter table public.lab_results add column interpretation text check(interpretation in ('normal','out_of_range','dangerously_abnormal'));
create or replace function private.interpret_lab_result() returns trigger language plpgsql security definer set search_path='' as $$
declare r public.lab_reference_ranges%rowtype;
begin
  if new.reference_range_id is null or new.numeric_value is null then return new; end if;
  select * into r from public.lab_reference_ranges where id=new.reference_range_id;
  new.reference_range=concat_ws(' - ',r.normal_low,r.normal_high);
  new.units=r.units;
  new.interpretation=case when (r.critical_low is not null and new.numeric_value<r.critical_low) or (r.critical_high is not null and new.numeric_value>r.critical_high) then 'dangerously_abnormal' when (r.normal_low is not null and new.numeric_value<r.normal_low) or (r.normal_high is not null and new.numeric_value>r.normal_high) then 'out_of_range' else 'normal' end;
  new.abnormal_flag=case new.interpretation when 'normal' then 'N' when 'out_of_range' then 'A' else 'C' end;
  return new;
end $$;
revoke all on function private.interpret_lab_result() from public,anon,authenticated;
create trigger interpret_lab_result before insert or update of numeric_value,reference_range_id on public.lab_results for each row execute function private.interpret_lab_result();

create table public.medication_lists (
  id bigint generated by default as identity primary key,
  facility_id uuid references public.facilities(id) on delete cascade,
  country_id bigint references public.countries(id),
  name text not null,
  authority text not null,
  version text not null,
  source_url text,
  active boolean not null default true,
  unique(facility_id,country_id,name,version)
);
create table public.medication_list_items (
  list_id bigint not null references public.medication_lists(id) on delete cascade,
  medication_id bigint not null references public.medications(id) on delete cascade,
  section text,
  dosage_form text,
  notes text,
  primary key(list_id,medication_id)
);
insert into public.medication_lists(name,authority,version,source_url) values('WHO Model List of Essential Medicines','World Health Organization','24th list (2025)','https://www.who.int/publications/i/item/B09474');

create table public.medication_interactions (
  id bigint generated by default as identity primary key,
  medication_a_id bigint not null references public.medications(id),
  medication_b_id bigint not null references public.medications(id),
  severity text not null check(severity in ('informational','moderate','major','contraindicated')),
  clinical_effect text not null,
  recommendation text not null,
  evidence_source text,
  check(medication_a_id<>medication_b_id),
  unique(medication_a_id,medication_b_id)
);
create table public.prescription_interaction_alerts (
  id bigint generated by default as identity primary key,
  medication_order_id bigint not null references public.medication_orders(id) on delete cascade,
  interaction_id bigint not null references public.medication_interactions(id),
  status text not null default 'pending' check(status in ('pending','acknowledged','confirmed','cancelled')),
  prescriber_user_id uuid references auth.users(id),
  acknowledgement_reason text,
  acknowledged_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.terminology_releases (
  id bigint generated by default as identity primary key,
  system text not null,
  version text not null,
  source_url text not null,
  imported_at timestamptz,
  active boolean not null default false,
  unique(system,version)
);
insert into public.terminology_releases(system,version,source_url,active) values('ICD-11 MMS','WHO ICD API v2 - release selected at import','https://id.who.int/',false);
create table public.diagnoses (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete cascade,
  encounter_id bigint references public.encounters(id),
  terminology_release_id bigint not null references public.terminology_releases(id),
  code text not null,
  entity_uri text not null,
  display text not null,
  language_code text not null default 'en',
  recorded_at timestamptz not null default now()
);

create table public.integration_endpoints (
  id bigint generated by default as identity primary key,
  facility_id uuid not null references public.facilities(id) on delete cascade,
  integration_type text not null check(integration_type in ('dhis2_web_api','dhis2_fhir','dicom_dimse','dicomweb_qido','dicomweb_wado','dicomweb_stow')),
  base_url text not null,
  enabled boolean not null default false,
  configuration jsonb not null default '{}'::jsonb,
  unique(facility_id,integration_type,base_url)
);

alter table public.facility_patient_mrns enable row level security;
alter table public.lab_reference_ranges enable row level security;
alter table public.medication_lists enable row level security;
alter table public.medication_list_items enable row level security;
alter table public.medication_interactions enable row level security;
alter table public.prescription_interaction_alerts enable row level security;
alter table public.terminology_releases enable row level security;
alter table public.diagnoses enable row level security;
alter table public.integration_endpoints enable row level security;
create policy facility_mrn_access on public.facility_patient_mrns for all to authenticated using(private.is_platform_root() or private.is_facility_member(facility_id)) with check(private.is_platform_root() or private.is_facility_member(facility_id));
create policy lab_ranges_access on public.lab_reference_ranges for all to authenticated using(private.is_platform_root() or facility_id is null or private.is_facility_member(facility_id)) with check(private.is_platform_root() or (facility_id is not null and private.is_facility_admin(facility_id)));
create policy medication_lists_read on public.medication_lists for select to authenticated using(facility_id is null or private.is_platform_root() or private.is_facility_member(facility_id));
create policy medication_lists_write on public.medication_lists for all to authenticated using(private.is_platform_root() or (facility_id is not null and private.is_facility_admin(facility_id))) with check(private.is_platform_root() or (facility_id is not null and private.is_facility_admin(facility_id)));
create policy medication_items_read on public.medication_list_items for select to authenticated using(exists(select 1 from public.medication_lists ml where ml.id=list_id and (ml.facility_id is null or private.is_platform_root() or private.is_facility_member(ml.facility_id))));
create policy medication_interactions_read on public.medication_interactions for select to authenticated using(true);
create policy medication_interactions_write on public.medication_interactions for all to authenticated using(private.is_platform_root()) with check(private.is_platform_root());
create policy interaction_alerts_access on public.prescription_interaction_alerts for all to authenticated using(private.is_platform_root() or exists(select 1 from public.medication_orders mo join public.patients p on p.id=mo.patient_id where mo.id=medication_order_id and p.facility_id is not null and private.is_facility_member(p.facility_id))) with check(private.is_platform_root() or exists(select 1 from public.medication_orders mo join public.patients p on p.id=mo.patient_id where mo.id=medication_order_id and p.facility_id is not null and private.is_facility_member(p.facility_id)));
create policy terminology_read on public.terminology_releases for select to authenticated using(true);
create policy terminology_write on public.terminology_releases for all to authenticated using(private.is_platform_root()) with check(private.is_platform_root());
create policy diagnoses_access on public.diagnoses for all to authenticated using(private.is_platform_root() or exists(select 1 from public.patients p where p.id=patient_id and p.facility_id is not null and private.is_facility_member(p.facility_id)) or exists(select 1 from public.patient_accounts pa where pa.patient_id=diagnoses.patient_id and pa.user_id=(select auth.uid()))) with check(private.is_platform_root() or exists(select 1 from public.patients p where p.id=patient_id and p.facility_id is not null and private.is_facility_member(p.facility_id)));
create policy integrations_access on public.integration_endpoints for all to authenticated using(private.is_platform_root() or private.is_facility_admin(facility_id)) with check(private.is_platform_root() or private.is_facility_admin(facility_id));
grant select,insert,update on public.facility_patient_mrns,public.lab_reference_ranges,public.medication_lists,public.medication_list_items,public.medication_interactions,public.prescription_interaction_alerts,public.terminology_releases,public.diagnoses,public.integration_endpoints to authenticated;
create index lab_reference_ranges_lookup_idx on public.lab_reference_ranges(analyte_code,facility_id,effective_from);
create index medication_interactions_pair_idx on public.medication_interactions(medication_a_id,medication_b_id);
create index diagnoses_patient_idx on public.diagnoses(patient_id,recorded_at desc);
