-- Rules sourced from the HC Students Health feature inventory and portal package.
insert into public.roles(role_code,role_name,description,access_level) values
 ('health_department_admin','Health Department Administrator','Jurisdiction-scoped public health oversight',2),
 ('health_department_analyst','Health Department Analyst','Jurisdiction reporting and authorized drill-down',3),
 ('support_agent','Support Team Member','Works tickets directed to an assigned support group',4),
 ('community_moderator','Community Moderator','Moderates assigned communities',4)
on conflict(role_code) do update set role_name=excluded.role_name,description=excluded.description;

create or replace function private.is_aal2() returns boolean language sql stable security invoker set search_path='' as $$
 select coalesce((select auth.jwt()->>'aal'),'')='aal2'
$$;

create table public.facility_branding(
 facility_id uuid primary key references public.facilities(id) on delete cascade,
 display_name text, logo_url text, primary_color text not null default '#187eb6' check(primary_color ~ '^#[0-9A-Fa-f]{6}$'),
 secondary_color text not null default '#d90000' check(secondary_color ~ '^#[0-9A-Fa-f]{6}$'),
 accent_color text not null default '#f28c28' check(accent_color ~ '^#[0-9A-Fa-f]{6}$'),
 background_color text not null default '#eef5f8' check(background_color ~ '^#[0-9A-Fa-f]{6}$'),
 font_family text not null default 'Inter, Segoe UI, sans-serif', updated_at timestamptz not null default now(), updated_by uuid references auth.users(id)
);

create table public.ehr_connections(
 id uuid primary key default gen_random_uuid(), facility_id uuid not null references public.facilities(id) on delete cascade,
 vendor text not null check(vendor in ('epic','oracle_health','generic_fhir_r4','hl7_v2','hie','iis')),
 name text not null, fhir_base_url text, authorization_url text, token_url text, client_id text,
 smart_launch_type text check(smart_launch_type in ('ehr_launch','standalone','both')), scopes text[] not null default '{}',
 secret_reference text, environment text not null default 'sandbox' check(environment in ('sandbox','test','production')),
 enabled boolean not null default false, last_tested_at timestamptz, last_test_status text, configuration jsonb not null default '{}'::jsonb,
 unique(facility_id,vendor,name)
);

create table public.health_jurisdictions(
 id uuid primary key default gen_random_uuid(), name text not null, jurisdiction_type text not null check(jurisdiction_type in ('country','state_province','county_district','city','health_district')),
 country_id bigint references public.countries(id), parent_id uuid references public.health_jurisdictions(id), boundary_reference text, active boolean not null default true
);
create table public.health_department_memberships(
 jurisdiction_id uuid not null references public.health_jurisdictions(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade,
 role_id bigint not null references public.roles(id), active boolean not null default true, primary key(jurisdiction_id,user_id)
);
create table public.facility_jurisdictions(
 facility_id uuid not null references public.facilities(id) on delete cascade, jurisdiction_id uuid not null references public.health_jurisdictions(id) on delete cascade,
 primary key(facility_id,jurisdiction_id)
);
create table public.health_heatmap_observations(
 id bigint generated by default as identity primary key, jurisdiction_id uuid not null references public.health_jurisdictions(id) on delete cascade,
 facility_id uuid references public.facilities(id) on delete cascade, metric_code text not null, metric_label text not null,
 period_start date not null, period_end date not null, geographic_label text not null, latitude numeric(9,6), longitude numeric(9,6),
 value numeric not null, population_denominator numeric, suppression_threshold integer not null default 5,
 source text not null, refreshed_at timestamptz not null default now(), check(period_end>=period_start)
);

create table public.subscription_plans(
 id uuid primary key default gen_random_uuid(), name text not null, currency char(3) not null, annual_facility_fee numeric(14,2) not null default 0,
 monthly_patient_fee numeric(14,2) not null default 0, active boolean not null default true, features jsonb not null default '{}'::jsonb
);
create table public.facility_subscriptions(
 id uuid primary key default gen_random_uuid(), facility_id uuid not null unique references public.facilities(id) on delete cascade,
 plan_id uuid not null references public.subscription_plans(id), status text not null default 'trialing' check(status in ('trialing','active','past_due','paused','cancelled')),
 patient_quantity integer not null default 0, current_period_start date, current_period_end date, external_customer_reference text,
 external_subscription_reference text, promotion_ends_at timestamptz, created_at timestamptz not null default now()
);

create table public.message_threads(
 id uuid primary key default gen_random_uuid(), facility_id uuid references public.facilities(id) on delete cascade,
 subject text not null, thread_type text not null check(thread_type in ('direct','group','facility_broadcast','health_department')),
 created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), archived_at timestamptz
);
create table public.message_participants(
 thread_id uuid not null references public.message_threads(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade,
 participant_role text not null default 'member' check(participant_role in ('owner','member')), archived_at timestamptz, last_read_at timestamptz, primary key(thread_id,user_id)
);
create table public.messages(
 id bigint generated by default as identity primary key, thread_id uuid not null references public.message_threads(id) on delete cascade,
 sender_user_id uuid not null references auth.users(id), body text not null, original_language text not null default 'en',
 reply_to_id bigint references public.messages(id), sent_at timestamptz not null default now(), deleted_at timestamptz
);

create table public.communities(
 id uuid primary key default gen_random_uuid(), title text not null unique, description text, visibility text not null check(visibility in ('public','private')),
 status text not null default 'active' check(status in ('proposed','active','suspended','closed')), created_by uuid not null references auth.users(id), created_at timestamptz not null default now()
);
create table public.community_memberships(
 community_id uuid not null references public.communities(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade,
 role text not null default 'member' check(role in ('creator','administrator','moderator','member')), status text not null default 'pending' check(status in ('pending','active','paused','blocked','declined')),
 joined_at timestamptz, notifications_paused boolean not null default false, primary key(community_id,user_id)
);
create table public.community_posts(
 id uuid primary key default gen_random_uuid(), community_id uuid not null references public.communities(id) on delete cascade,
 author_user_id uuid not null references auth.users(id), body text not null, original_language text not null default 'en', attachment_metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(), deleted_at timestamptz, moderation_state text not null default 'visible' check(moderation_state in ('visible','under_review','removed','evidence_preserved'))
);
create table public.community_comments(
 id bigint generated by default as identity primary key, post_id uuid not null references public.community_posts(id) on delete cascade,
 author_user_id uuid not null references auth.users(id), body text not null, original_language text not null default 'en', created_at timestamptz not null default now(), deleted_at timestamptz
);
create table public.community_reactions(
 post_id uuid not null references public.community_posts(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade,
 reaction text not null check(reaction in ('like','dislike')), created_at timestamptz not null default now(), primary key(post_id,user_id)
);
create table public.community_moderation_actions(
 id bigint generated by default as identity primary key, community_id uuid not null references public.communities(id), post_id uuid references public.community_posts(id),
 target_user_id uuid references auth.users(id), action text not null check(action in ('warning','remove','preserve_evidence','suspend','block','escalate')),
 reason text not null, actor_user_id uuid not null references auth.users(id), created_at timestamptz not null default now()
);

create or replace function private.is_thread_participant(tid uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.message_participants where thread_id=tid and user_id=(select auth.uid()))
$$;
create or replace function private.is_thread_owner(tid uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.message_participants where thread_id=tid and user_id=(select auth.uid()) and participant_role='owner')
$$;
create or replace function private.has_community_access(cid uuid,active_only boolean default false) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.community_memberships where community_id=cid and user_id=(select auth.uid()) and status=case when active_only then 'active' else status end and status in ('active','paused'))
$$;
create or replace function private.manages_community(cid uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.community_memberships where community_id=cid and user_id=(select auth.uid()) and role in ('creator','administrator','moderator') and status='active')
$$;
revoke all on function private.is_thread_participant(uuid),private.is_thread_owner(uuid),private.has_community_access(uuid,boolean),private.manages_community(uuid) from public,anon,authenticated;

create or replace function public.set_community_notifications(community_to_change uuid,pause_notifications boolean) returns void language plpgsql security definer set search_path='' as $$
begin
 if not private.is_aal2() then raise exception 'MFA verification required'; end if;
 update public.community_memberships set notifications_paused=pause_notifications,status=case when pause_notifications then 'paused' else 'active' end
 where community_id=community_to_change and user_id=(select auth.uid()) and status in ('active','paused');
 if not found then raise exception 'Active community membership required'; end if;
end $$;
revoke all on function public.set_community_notifications(uuid,boolean) from public,anon;
grant execute on function public.set_community_notifications(uuid,boolean) to authenticated;

create or replace function private.community_creator_membership() returns trigger language plpgsql security definer set search_path='' as $$
begin
 insert into public.community_memberships(community_id,user_id,role,status,joined_at) values(new.id,new.created_by,'creator','active',now());
 return new;
end $$;
create trigger community_creator_membership after insert on public.communities for each row execute function private.community_creator_membership();

create table public.support_groups(
 id uuid primary key default gen_random_uuid(), facility_id uuid references public.facilities(id) on delete cascade, name text not null, group_type text not null check(group_type in ('healthcarology','facility','clinical','billing','technical')), unique(facility_id,name)
);
create table public.support_group_members(
 group_id uuid not null references public.support_groups(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, active boolean not null default true, primary key(group_id,user_id)
);
create table public.support_tickets(
 id uuid primary key default gen_random_uuid(), ticket_number text unique not null default 'SUP-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,12)),
 facility_id uuid references public.facilities(id), patient_id bigint references public.patients(id), directed_group_id uuid not null references public.support_groups(id),
 subject text not null, priority text not null default 'normal' check(priority in ('low','normal','high','urgent')),
 status text not null default 'open' check(status in ('open','pending','grabbed','processing','closed','resolved')),
 created_by uuid not null references auth.users(id), assigned_to uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), closed_at timestamptz
);
create table public.support_ticket_messages(
 id bigint generated by default as identity primary key, ticket_id uuid not null references public.support_tickets(id) on delete cascade,
 sender_user_id uuid not null references auth.users(id), body text not null, created_at timestamptz not null default now()
);

create table public.patient_record_shares(
 id uuid primary key default gen_random_uuid(), patient_id bigint not null references public.patients(id) on delete cascade,
 grantor_user_id uuid not null references auth.users(id), grantee_identifier text not null, grantee_identifier_type text not null check(grantee_identifier_type in ('email','phone')),
 access_level text not null check(access_level in ('read_only','read_write')), share_scope text not null check(share_scope in ('complete','partial')),
 period_start date, period_end date, included_elements text[] not null default '{}', token_hash text unique not null, password_hash text not null,
 starts_at timestamptz not null default now(), expires_at timestamptz not null, status text not null default 'active' check(status in ('active','expired','revoked')),
 mfa_confirmed_at timestamptz not null, created_at timestamptz not null default now(), check(expires_at>starts_at), check(share_scope='complete' or array_length(included_elements,1)>0)
);
create table public.share_extension_requests(
 id uuid primary key default gen_random_uuid(), share_id uuid not null references public.patient_record_shares(id) on delete cascade,
 requested_until timestamptz not null, reason text, status text not null default 'pending' check(status in ('pending','approved','declined')),
 requested_at timestamptz not null default now(), responded_at timestamptz, responded_by uuid references auth.users(id)
);

create table public.billing_code_catalogs(
 id uuid primary key default gen_random_uuid(), country_code char(2) not null, code_system text not null, source_name text not null, source_url text,
 license_required boolean not null default false, version text, active boolean not null default true, unique(country_code,code_system,source_name,version)
);
create table public.billing_codes(
 id bigint generated by default as identity primary key, catalog_id uuid references public.billing_code_catalogs(id), facility_id uuid references public.facilities(id),
 country_code char(2) not null, code text not null, description text not null, currency char(3), price numeric(14,2), price_type text check(price_type in ('facility','national_average','copay','custom')),
 effective_from date, effective_to date, source_reference text, manually_entered boolean not null default false, active boolean not null default true,
 unique(facility_id,code,effective_from)
);
insert into public.billing_code_catalogs(country_code,code_system,source_name,source_url,license_required,version) values
 ('US','HCPCS Level II','NLM Clinical Tables','https://clinicaltables.nlm.nih.gov/api/hcpcs/v3/search',false,'live API'),
 ('US','CPT/HCPCS pricing','CMS Procedure Price Lookup','https://developer.cms.gov/ppl-api/',true,'annual')
on conflict do nothing;

-- Security and grants.
do $$ declare t text; begin foreach t in array array['facility_branding','ehr_connections','health_jurisdictions','health_department_memberships','facility_jurisdictions','health_heatmap_observations','subscription_plans','facility_subscriptions','message_threads','message_participants','messages','communities','community_memberships','community_posts','community_comments','community_reactions','community_moderation_actions','support_groups','support_group_members','support_tickets','support_ticket_messages','patient_record_shares','share_extension_requests','billing_code_catalogs','billing_codes'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;

create policy branding_read on public.facility_branding for select to authenticated using(private.is_aal2() and (private.is_platform_root() or private.is_facility_member(facility_id)));
create policy branding_admin_write on public.facility_branding for all to authenticated using(private.is_aal2() and (private.is_platform_root() or private.is_facility_admin(facility_id))) with check(private.is_aal2() and (private.is_platform_root() or private.is_facility_admin(facility_id)));
create policy ehr_connections_admin on public.ehr_connections for all to authenticated using(private.is_aal2() and (private.is_platform_root() or private.is_facility_admin(facility_id))) with check(private.is_aal2() and (private.is_platform_root() or private.is_facility_admin(facility_id)));
create policy jurisdictions_member_read on public.health_jurisdictions for select to authenticated using(private.is_aal2() and (private.is_platform_root() or exists(select 1 from public.health_department_memberships hm where hm.jurisdiction_id=id and hm.user_id=(select auth.uid()) and hm.active)));
create policy health_memberships_access on public.health_department_memberships for select to authenticated using(private.is_aal2() and (private.is_platform_root() or user_id=(select auth.uid())));
create policy facility_jurisdictions_read on public.facility_jurisdictions for select to authenticated using(private.is_aal2() and (private.is_platform_root() or private.is_facility_member(facility_id) or exists(select 1 from public.health_department_memberships hm where hm.jurisdiction_id=facility_jurisdictions.jurisdiction_id and hm.user_id=(select auth.uid()) and hm.active)));
create policy heatmap_authorized_read on public.health_heatmap_observations for select to authenticated using(private.is_aal2() and (private.is_platform_root() or (facility_id is not null and private.is_facility_member(facility_id)) or exists(select 1 from public.health_department_memberships hm where hm.jurisdiction_id=health_heatmap_observations.jurisdiction_id and hm.user_id=(select auth.uid()) and hm.active)));
create policy heatmap_admin_write on public.health_heatmap_observations for all to authenticated using(private.is_aal2() and private.is_platform_root()) with check(private.is_aal2() and private.is_platform_root());
create policy plans_authenticated_read on public.subscription_plans for select to authenticated using(private.is_aal2());
create policy plans_root_write on public.subscription_plans for all to authenticated using(private.is_aal2() and private.is_platform_root()) with check(private.is_aal2() and private.is_platform_root());
create policy facility_subscription_access on public.facility_subscriptions for select to authenticated using(private.is_aal2() and (private.is_platform_root() or private.is_facility_admin(facility_id)));
create policy facility_subscription_root_write on public.facility_subscriptions for all to authenticated using(private.is_aal2() and private.is_platform_root()) with check(private.is_aal2() and private.is_platform_root());

create policy threads_participant_read on public.message_threads for select to authenticated using(private.is_aal2() and private.is_thread_participant(id));
create policy threads_create on public.message_threads for insert to authenticated with check(private.is_aal2() and created_by=(select auth.uid()) and (facility_id is null or private.is_facility_member(facility_id)));
create policy participants_read on public.message_participants for select to authenticated using(private.is_aal2() and private.is_thread_participant(thread_id));
create policy participants_owner_write on public.message_participants for all to authenticated using(private.is_aal2() and private.is_thread_owner(thread_id)) with check(private.is_aal2());
create policy messages_participant_read on public.messages for select to authenticated using(private.is_aal2() and private.is_thread_participant(thread_id));
create policy messages_participant_send on public.messages for insert to authenticated with check(private.is_aal2() and sender_user_id=(select auth.uid()) and private.is_thread_participant(thread_id));

create policy communities_read on public.communities for select to authenticated using(private.is_aal2() and (visibility='public' or private.has_community_access(id,false)));
create policy communities_create on public.communities for insert to authenticated with check(private.is_aal2() and created_by=(select auth.uid()));
create policy community_members_read on public.community_memberships for select to authenticated using(private.is_aal2() and (user_id=(select auth.uid()) or private.manages_community(community_id)));
create policy community_members_join on public.community_memberships for insert to authenticated with check(private.is_aal2() and user_id=(select auth.uid()) and role='member' and status=case when (select visibility from public.communities where id=community_id)='public' then 'active' else 'pending' end);
create policy community_members_manage on public.community_memberships for update to authenticated using(private.is_aal2() and private.manages_community(community_id)) with check(private.is_aal2() and role in ('administrator','moderator','member') and status in ('pending','active','paused','blocked','declined'));
create policy community_posts_read on public.community_posts for select to authenticated using(private.is_aal2() and deleted_at is null and private.has_community_access(community_id,false));
create policy community_posts_write on public.community_posts for insert to authenticated with check(private.is_aal2() and author_user_id=(select auth.uid()) and private.has_community_access(community_id,true));
create policy community_comments_access on public.community_comments for all to authenticated using(private.is_aal2() and exists(select 1 from public.community_posts p where p.id=post_id and private.has_community_access(p.community_id,false))) with check(private.is_aal2() and author_user_id=(select auth.uid()));
create policy community_reactions_access on public.community_reactions for all to authenticated using(private.is_aal2() and user_id=(select auth.uid())) with check(private.is_aal2() and user_id=(select auth.uid()));
create policy moderation_access on public.community_moderation_actions for all to authenticated using(private.is_aal2() and private.manages_community(community_id)) with check(private.is_aal2());

create policy support_groups_read on public.support_groups for select to authenticated using(private.is_aal2() and (facility_id is null or private.is_facility_member(facility_id) or exists(select 1 from public.support_group_members gm where gm.group_id=id and gm.user_id=(select auth.uid()) and gm.active)));
create policy support_group_members_self on public.support_group_members for select to authenticated using(private.is_aal2() and user_id=(select auth.uid()));
create policy tickets_read on public.support_tickets for select to authenticated using(private.is_aal2() and (created_by=(select auth.uid()) or exists(select 1 from public.support_group_members gm where gm.group_id=directed_group_id and gm.user_id=(select auth.uid()) and gm.active)));
create policy tickets_create on public.support_tickets for insert to authenticated with check(private.is_aal2() and created_by=(select auth.uid()));
create policy tickets_group_update on public.support_tickets for update to authenticated using(private.is_aal2() and exists(select 1 from public.support_group_members gm where gm.group_id=directed_group_id and gm.user_id=(select auth.uid()) and gm.active)) with check(private.is_aal2());
create policy ticket_messages_read on public.support_ticket_messages for select to authenticated using(private.is_aal2() and exists(select 1 from public.support_tickets t where t.id=ticket_id and (t.created_by=(select auth.uid()) or exists(select 1 from public.support_group_members gm where gm.group_id=t.directed_group_id and gm.user_id=(select auth.uid()) and gm.active))));
create policy ticket_messages_send on public.support_ticket_messages for insert to authenticated with check(private.is_aal2() and sender_user_id=(select auth.uid()) and exists(select 1 from public.support_tickets t where t.id=ticket_id and t.status not in ('closed','resolved') and (t.created_by=(select auth.uid()) or exists(select 1 from public.support_group_members gm where gm.group_id=t.directed_group_id and gm.user_id=(select auth.uid()) and gm.active))));

create policy shares_grantor_access on public.patient_record_shares for select to authenticated using(private.is_aal2() and grantor_user_id=(select auth.uid()));
create policy shares_grantor_create on public.patient_record_shares for insert to authenticated with check(private.is_aal2() and grantor_user_id=(select auth.uid()) and exists(select 1 from public.patients p where p.id=patient_id and (exists(select 1 from public.patient_accounts pa where pa.patient_id=p.id and pa.user_id=(select auth.uid())) or (p.facility_id is not null and private.has_facility_role(p.facility_id,array['physician','resident','advanced_practice'])))));
create policy shares_grantor_update on public.patient_record_shares for update to authenticated using(private.is_aal2() and grantor_user_id=(select auth.uid())) with check(private.is_aal2() and grantor_user_id=(select auth.uid()));
create policy extensions_grantor_read on public.share_extension_requests for select to authenticated using(private.is_aal2() and exists(select 1 from public.patient_record_shares s where s.id=share_id and s.grantor_user_id=(select auth.uid())));
create policy extensions_grantor_update on public.share_extension_requests for update to authenticated using(private.is_aal2() and exists(select 1 from public.patient_record_shares s where s.id=share_id and s.grantor_user_id=(select auth.uid()))) with check(private.is_aal2());
create policy billing_catalogs_read on public.billing_code_catalogs for select to authenticated using(private.is_aal2());
create policy billing_catalogs_root on public.billing_code_catalogs for all to authenticated using(private.is_aal2() and private.is_platform_root()) with check(private.is_aal2() and private.is_platform_root());
create policy billing_codes_read on public.billing_codes for select to authenticated using(private.is_aal2() and (facility_id is null or private.is_facility_member(facility_id)));
create policy billing_codes_write on public.billing_codes for all to authenticated using(private.is_aal2() and facility_id is not null and private.has_facility_role(facility_id,array['sysadmin','billing'])) with check(private.is_aal2() and facility_id is not null and private.has_facility_role(facility_id,array['sysadmin','billing']));

grant select,insert,update,delete on public.facility_branding,public.ehr_connections,public.health_jurisdictions,public.health_department_memberships,public.facility_jurisdictions,public.health_heatmap_observations,public.subscription_plans,public.facility_subscriptions,public.message_threads,public.message_participants,public.messages,public.communities,public.community_memberships,public.community_posts,public.community_comments,public.community_reactions,public.community_moderation_actions,public.support_groups,public.support_group_members,public.support_tickets,public.support_ticket_messages,public.patient_record_shares,public.share_extension_requests,public.billing_code_catalogs,public.billing_codes to authenticated;
create index heatmap_lookup_idx on public.health_heatmap_observations(jurisdiction_id,metric_code,period_start,period_end);
create index messages_thread_idx on public.messages(thread_id,sent_at);
create index community_posts_idx on public.community_posts(community_id,created_at desc) where deleted_at is null;
create index tickets_queue_idx on public.support_tickets(directed_group_id,status,priority,created_at);
create index shares_active_idx on public.patient_record_shares(patient_id,expires_at) where status='active';
create index billing_codes_lookup_idx on public.billing_codes(code,country_code) where active;
