create table public.shared_record_access_audit(
 id bigint generated by default as identity primary key, share_id uuid not null references public.patient_record_shares(id) on delete cascade,
 action text not null check(action in ('view','download','contribute','extension_request','failed_login')), occurred_at timestamptz not null default now(),
 grantee_identifier text, ip_hash text, user_agent text, details jsonb not null default '{}'::jsonb
);
create table public.shared_record_contributions(
 id uuid primary key default gen_random_uuid(), share_id uuid not null references public.patient_record_shares(id) on delete cascade,
 patient_id bigint not null references public.patients(id) on delete cascade, contributor_identifier text not null,
 entry_type text not null check(entry_type in ('note','document_reference','correction_request','clinical_update')),
 content text not null, created_at timestamptz not null default now(), review_status text not null default 'unreviewed' check(review_status in ('unreviewed','accepted','rejected')),
 reviewed_by uuid references auth.users(id), reviewed_at timestamptz
);
alter table public.shared_record_access_audit enable row level security;
alter table public.shared_record_contributions enable row level security;
create or replace function private.protect_shared_contribution() returns trigger language plpgsql security invoker set search_path='' as $$
begin
 if new.share_id<>old.share_id or new.patient_id<>old.patient_id or new.contributor_identifier<>old.contributor_identifier or new.entry_type<>old.entry_type or new.content<>old.content or new.created_at<>old.created_at then
  raise exception 'Shared contribution identity and content are immutable';
 end if;
 return new;
end $$;
create trigger protect_shared_contribution before update on public.shared_record_contributions for each row execute function private.protect_shared_contribution();
create policy share_audit_grantor_read on public.shared_record_access_audit for select to authenticated using(private.is_aal2() and exists(select 1 from public.patient_record_shares s where s.id=share_id and s.grantor_user_id=(select auth.uid())));
create policy contributions_authorized_read on public.shared_record_contributions for select to authenticated using(private.is_aal2() and exists(select 1 from public.patient_record_shares s join public.patients p on p.id=s.patient_id where s.id=share_id and (s.grantor_user_id=(select auth.uid()) or (p.facility_id is not null and private.has_facility_role(p.facility_id,array['physician','resident','advanced_practice'])))));
create policy contributions_provider_review on public.shared_record_contributions for update to authenticated using(private.is_aal2() and exists(select 1 from public.patients p where p.id=patient_id and p.facility_id is not null and private.has_facility_role(p.facility_id,array['physician','resident','advanced_practice']))) with check(private.is_aal2() and reviewed_by=(select auth.uid()) and review_status in ('accepted','rejected'));
grant select on public.shared_record_access_audit,public.shared_record_contributions to authenticated;
grant update on public.shared_record_contributions to authenticated;
create index share_audit_idx on public.shared_record_access_audit(share_id,occurred_at desc);
create index share_contributions_idx on public.shared_record_contributions(patient_id,created_at desc);
