-- Geographic names sourced from GeoNames admin1CodesASCII.txt and cities15000.txt on 2026-08-27.
with country as (select id from public.countries where iso2='CD') insert into public.provinces(country_id,code,default_name,type) values
((select id from country),'31','Tshuapa','province'),
((select id from country),'30','Tshopo','province'),
((select id from country),'29','Tanganyika','province'),
((select id from country),'12','South Kivu','province'),
((select id from country),'27','Sankuru','province'),
((select id from country),'11','North Kivu','province'),
((select id from country),'25','Mongala','province'),
((select id from country),'10','Maniema','province'),
((select id from country),'23','Kasai-Central','province'),
((select id from country),'04','East Kasai','province'),
((select id from country),'18','Kasai','province'),
((select id from country),'17','Ituri','province'),
((select id from country),'16','Haut-Uele','province'),
((select id from country),'15','Haut-Lomami','province'),
((select id from country),'02','Équateur','province'),
((select id from country),'13','Bas-Uele','province'),
((select id from country),'22','Lualaba','province'),
((select id from country),'24','Mai-Ndombe','province'),
((select id from country),'20','Kwilu','province'),
((select id from country),'19','Kwango','province'),
((select id from country),'06','Kinshasa','province'),
((select id from country),'08','Bas-Congo','province'),
((select id from country),'14','Haut-Katanga','province'),
((select id from country),'21','Lomami','province'),
((select id from country),'26','Nord-Ubangi','province'),
((select id from country),'28','Sud-Ubangi','province') on conflict do nothing;
with country as (select id from public.countries where iso2='CD') insert into public.cities(country_id,province_id,default_name,latitude,longitude) values
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='30' limit 1),'Yangambi',0.76755,24.43973),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='16' limit 1),'Watsa',3.03716,29.53551),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='16' limit 1),'Wamba',2.14838,27.99466),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='12' limit 1),'Uvira',-3.39534,29.13779),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='18' limit 1),'Tshikapa',-6.41621,20.79995),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='11' limit 1),'Sake',-1.57386,29.04339),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='11' limit 1),'Rutshuru',-1.18666,29.44669),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='14' limit 1),'Pweto',-8.46604,28.90079),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='29' limit 1),'Pepa',-7.69811,29.7772),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='29' limit 1),'Nyunzu',-5.95609,28.01649),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='21' limit 1),'Mwene-Ditu',-7.00906,23.45278),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='18' limit 1),'Mweka',-4.85187,21.5595),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='15' limit 1),'Mulongo',-7.83486,26.99852),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='17' limit 1),'Mangbwalu',1.94468,30.03861),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='29' limit 1),'Baudhuinville',-7.08408,29.73681),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='04' limit 1),'Miabi',-6.22149,23.39254),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='04' limit 1),'Mbuji-Mayi',-6.13603,23.58979),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='29' limit 1),'Manono',-7.29862,27.39894),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='15' limit 1),'Malemba-Nkulu',-8.04475,26.79625),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='27' limit 1),'Lusambo',-4.97503,23.44391),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='21' limit 1),'Luputa',-7.16177,23.70057),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='27' limit 1),'Lukula',-3.86881,23.88348),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='18' limit 1),'Luebo',-5.35218,21.42192),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='11' limit 1),'Lubero',-0.15837,29.23859),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='21' limit 1),'Lubao',-5.38771,25.74885),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='27' limit 1),'Lodja',-3.52105,23.6005),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='25' limit 1),'Lisala',2.15127,21.51672),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='29' limit 1),'Kongolo',-5.38532,27.00029),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='30' limit 1),'Kisangani',0.51528,25.19099),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='11' limit 1),'Kirumba',-1.09056,29.2925),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='15' limit 1),'Kipamba',-8.20591,26.42036),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='10' limit 1),'Kindu',-2.94373,25.92237),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='11' limit 1),'Kayna',-0.60927,29.17249),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='11' limit 1),'Katwa',0.08928,29.30858),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='11' limit 1),'Katanda',-0.82535,29.36451),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='10' limit 1),'Kasongo',-4.42741,26.66656),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='11' limit 1),'Kanyobagonga',-0.69978,29.17181),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='15' limit 1),'Kanyama',-7.51668,24.17404),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='23' limit 1),'Kananga',-5.89624,22.41659),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='10' limit 1),'Kampene',-3.59678,26.66715),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='15' limit 1),'Kamina',-8.73508,24.99798),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='29' limit 1),'Kalima',-5.4854,28.21601),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='29' limit 1),'Kalemie',-5.94749,29.19471),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='21' limit 1),'Kabinda',-6.13791,24.48179),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='04' limit 1),'Kabeya-Kamwanga',-5.9988,23.25386),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='12' limit 1),'Kabare',-2.49682,28.79081),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='29' limit 1),'Kabalo',-6.05255,26.9143),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='16' limit 1),'Isiro',2.77391,27.61603),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='18' limit 1),'Ilebo',-4.33111,20.58638),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='11' limit 1),'Goma',-1.67409,29.22845),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='26' limit 1),'Gbadolite',4.279,21.00284),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='21' limit 1),'Gandajika',-6.74504,23.95328),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='17' limit 1),'Djugu',1.91932,30.50257),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='23' limit 1),'Demba',-5.49573,22.26962),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='11' limit 1),'Butembo',0.14164,29.29117),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='13' limit 1),'Buta',2.78582,24.72997),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='26' limit 1),'Businga',3.33863,20.88577),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='17' limit 1),'Bunia',1.55941,30.25224),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='25' limit 1),'Bumba',2.18771,22.46827),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='12' limit 1),'Bukavu',-2.49077,28.84281),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='15' limit 1),'Bukama',-9.20443,25.85475),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='13' limit 1),'Bondo',3.81461,23.68665),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='31' limit 1),'Boende',-0.28163,20.88053),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='25' limit 1),'Binga',2.37351,20.49769),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='11' limit 1),'Beni',0.49113,29.47306),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='30' limit 1),'Basoko',1.23909,23.61598),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='16' limit 1),'Bakwa',4.1263,27.39527),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='30' limit 1),'Babamba',0.18333,27.48333),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='17' limit 1),'Aru',2.86218,30.84138),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='13' limit 1),'Aketi',2.73877,23.78326),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='22' limit 1),'Tshilenge',-10.96667,22.9),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='14' limit 1),'Mokambo',-12.42765,28.34684),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='22' limit 1),'Malemba',-10.37812,24.54516),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='14' limit 1),'Lubumbashi',-11.66089,27.47938),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='14' limit 1),'Likasi',-10.98303,26.7384),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='22' limit 1),'Kolwezi',-10.71484,25.46674),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='14' limit 1),'Kipushi',-11.76097,27.25135),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='14' limit 1),'Kambove',-10.87352,26.59746),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='22' limit 1),'Fungurume',-10.61771,26.32107),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='28' limit 1),'Zongo',4.34283,18.59447),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='08' limit 1),'Tshela',-4.99707,12.9484),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='24' limit 1),'Nioki',-2.72037,17.69001),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='24' limit 1),'Mushie',-3.01728,16.92238),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='08' limit 1),'Moanda',-5.92753,12.37148),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='08' limit 1),'Mbanza-Ngungu',-5.25837,14.85838),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='02' limit 1),'Mbandaka',0.04865,18.26034),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='08' limit 1),'Matadi',-5.83861,13.46306),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='20' limit 1),'Masi-Manimba',-4.77549,17.89095),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='20' limit 1),'Mangai',-4.02328,19.53385),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='28' limit 1),'Libenge',3.65332,18.63566),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='24' limit 1),'Kutu',-2.7249,18.14756),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='06' limit 1),'Kinshasa',-4.32758,15.31357),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='08' limit 1),'Kimpese',-5.5615,14.43159),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='20' limit 1),'Kikwit',-5.04098,18.81619),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='08' limit 1),'Kenge',-5.76521,13.65711),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='19' limit 1),'Kasongo-Lunda',-6.47833,16.81735),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='08' limit 1),'Kasangulu',-4.5833,15.16554),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='24' limit 1),'Inongo',-1.9275,18.2881),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='08' limit 1),'Inkisi',-5.13122,15.0541),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='20' limit 1),'Idiofa',-4.96589,19.59151),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='28' limit 1),'Gemena',3.25651,19.77234),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='24' limit 1),'Dungu',-3.62437,18.84943),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='20' limit 1),'Dibaya-Lubwe',-4.15869,19.8619),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='20' limit 1),'Bulungu',-4.54437,18.60364),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='08' limit 1),'Boma',-5.85098,13.05364),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='24' limit 1),'Bolobo',-2.158,16.23249),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='02' limit 1),'Bolenge',0,18.21667),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='02' limit 1),'Basankusu',1.22095,19.80205),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='20' limit 1),'Bandundu Province',-3.31687,17.38063),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='06' limit 1),'Masina',-4.38361,15.39139),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='11' limit 1),'Hyosha',0.69781,29.51863),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='22' limit 1),'Mwene',-9.81697,22.87023),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='29' limit 1),'Kituku',-7.58157,30.20604),
((select id from country),(select id from public.provinces where country_id=(select id from country) and code='11' limit 1),'Mangina',0.60419,29.31004);
create index if not exists provinces_country_name_idx on public.provinces(country_id,default_name);
create index if not exists cities_country_province_name_idx on public.cities(country_id,province_id,default_name);
grant select on public.provinces,public.cities to authenticated;